global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # VoaLive API monitoring
  - job_name: 'voalive-api'
    static_configs:
      - targets: ['voalive-api:4000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # VoaLive Web monitoring
  - job_name: 'voalive-web'
    static_configs:
      - targets: ['voalive-web:3003']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # PostgreSQL monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis monitoring
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Traefik monitoring
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'

  # Flight Scraping Jobs monitoring (custom metrics)
  - job_name: 'flight-scraper-jobs'
    static_configs:
      - targets: ['voalive-api:4000']
    metrics_path: '/api/v1/flight-scraper/metrics'
    scrape_interval: 60s