import { Flight } from '@reservasegura/types';

export const mockFlights: Flight[] = [
  {
    id: '1',
    flightNumber: 'AD2456',
    origin: 'BSB',
    destination: 'GRU',
    departureTime: new Date('2024-03-20T10:00:00'),
    arrivalTime: new Date('2024-03-20T12:30:00'),
    airline: 'AZUL',
    aircraft: 'A320',
    status: 'CONFIRMADO',
    checkInStatus: 'OPEN',
    locator: 'ABC123',
    passengerFirstName: 'João',
    passengerLastName: 'Silva',
  },
  {
    id: '2',
    flightNumber: 'LA3789',
    origin: 'GRU',
    destination: 'REC',
    departureTime: new Date('2024-03-21T14:00:00'),
    arrivalTime: new Date('2024-03-21T17:00:00'),
    airline: 'LATAM',
    aircraft: 'B737',
    status: 'SCHEDULED',
    checkInStatus: 'CLOSED',
    locator: 'XYZ789',
    passengerFirstName: 'Maria',
    passengerLastName: 'Santos',
  },
  {
    id: '3',
    flightNumber: 'G31234',
    origin: 'CGH',
    destination: 'XAP',
    departureTime: new Date('2024-03-22T08:00:00'),
    arrivalTime: new Date('2024-03-22T10:30:00'),
    airline: 'GOL',
    aircraft: 'B737',
    status: 'SCHEDULED',
    checkInStatus: 'NOT_AVAILABLE',
    locator: 'DEF456',
    passengerFirstName: 'Pedro',
    passengerLastName: 'Costa',
  },
  {
    id: '4',
    flightNumber: 'AD7890',
    origin: 'CNF',
    destination: 'FOR',
    departureTime: new Date('2024-03-23T16:00:00'),
    arrivalTime: new Date('2024-03-23T18:45:00'),
    airline: 'AZUL',
    aircraft: 'E195',
    status: 'DELAYED',
    checkInStatus: 'OPEN',
    locator: 'GHI789',
    passengerFirstName: 'Ana',
    passengerLastName: 'Oliveira',
  },
  {
    id: '5',
    flightNumber: 'LA5432',
    origin: 'SSA',
    destination: 'POA',
    departureTime: new Date('2024-03-24T07:30:00'),
    arrivalTime: new Date('2024-03-24T10:15:00'),
    airline: 'LATAM',
    aircraft: 'A320',
    status: 'BOARDING',
    checkInStatus: 'CLOSED',
    locator: 'JKL012',
    passengerFirstName: 'Carlos',
    passengerLastName: 'Ferreira',
  },
  {
    id: '6',
    flightNumber: 'G36789',
    origin: 'CWB',
    destination: 'BEL',
    departureTime: new Date('2024-03-18T12:00:00'),
    arrivalTime: new Date('2024-03-18T15:30:00'),
    airline: 'GOL',
    aircraft: 'B737',
    status: 'ARRIVED',
    checkInStatus: 'COMPLETED',
    locator: 'MNO345',
    passengerFirstName: 'Lucia',
    passengerLastName: 'Mendes',
  },
  {
    id: '7',
    flightNumber: 'AD1122',
    origin: 'MAO',
    destination: 'VCP',
    departureTime: new Date('2024-03-25T09:00:00'),
    arrivalTime: new Date('2024-03-25T13:00:00'),
    airline: 'AZUL',
    aircraft: 'A321',
    status: 'SCHEDULED',
    checkInStatus: 'NOT_AVAILABLE',
    locator: 'PQR678',
    passengerFirstName: 'Roberto',
    passengerLastName: 'Lima',
  },
  {
    id: '8',
    flightNumber: 'LA9876',
    origin: 'FLN',
    destination: 'GIG',
    departureTime: new Date('2024-03-19T20:00:00'),
    arrivalTime: new Date('2024-03-19T21:30:00'),
    airline: 'LATAM',
    aircraft: 'A319',
    status: 'CANCELLED',
    checkInStatus: 'NOT_AVAILABLE',
    locator: 'STU901',
    passengerFirstName: 'Fernanda',
    passengerLastName: 'Rocha',
  },
];
